lazy
baydindima/JavaCourse pull request #1
Opened 2016-09-11 07:40 UTC by baydindima

first homework

2016-09-16 12:07 UTC, jzuken commented on src/main/java/homework1/SingleLazy.java
> +        if (supplier != null) {
а как мы отличим null, который пришёл от supplier'а, от просто пустого значения при инициализации?

2016-09-16 12:07 UTC, jzuken requested changes

2016-09-16 12:56 UTC, baydindima commented on src/main/java/homework1/SingleLazy.java
> +        if (supplier != null) {
Всмысле нужно учитывать ситуацию, когда supplier == null при инициализации?

2016-09-20 19:43 UTC, jzuken commented on src/main/java/homework1/SingleLazy.java
> +        if (supplier != null) {
а, нет, я ерунду написал

2016-09-21 08:52 UTC, merged